max_availability_zones: 3
az_mapping: false
subnet_multiplyer: 4

vpc_cidr: 10.0.0.0/16
subnet_mask: 24
subnet_parameters: false

subnets:
  public:
    name: Public
    type: public
    enable: true
  compute:
    name: Compute
    type: private
    enable: true
  persistence:
    name: Persistence
    type: private
    enable: true
  cache:
    name: Cache
    type: private
    enable: true

acl_rules:
  -
    acl: public
    number: 100
    from: 80
    ips:
      - public
  -
    acl: public
    number: 150
    from: 443
    ips:
      - public
  -
    acl: public
    number: 200
    from: 1024
    to: 65535
    ips:
      - public
  -
    acl: private
    number: 100
    protocol: -1 
    ips:
      - public
  -
    acl: private
    egress: true
    number: 100
    protocol: -1
    ips:
      - public
  -
    acl: public
    number: 100
    egress: true
    protocol: -1
    ips:
      - public
      
dns_format: ${EnvironmentName}.${DnsDomain}

enable_transit_vpc: true
enable_dhcp: true

create_hosted_zone: true
manage_ns_records: false

endpoint_subnets: Compute

ip_blocks:
  public:
    - 0.0.0.0/0

nat_iam_policies:
  eni-attach:
    action: ec2:AttachNetworkInterface
